### ISSUE TITLE
npm install还有 npm run build时，会碰到一大堆提示依赖问题

### ISSUE THREAD

**Issue by haisom2022** [star7th/showdoc#2111]
我的 node -v  是v21.4.0  npm -v 是10.2.4

git下来的版本，执行npm install无法进行

haisom@HaicodeMacBook-Pro-2 web_src % rm -rf package-lock.json
haisom@HaicodeMacBook-Pro-2 web_src % npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: showdoc@1.0.0
npm ERR! Found: webpack@3.12.0
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"^3.12.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^5.0.0" from style-loader@3.3.3
npm ERR! node_modules/style-loader
npm ERR!   dev style-loader@"^3.3.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/haisom/.npm/_logs/2023-12-09T08_32_49_043Z-eresolve-report.txt
npm ERR! A complete log of this run can be found in: /Users/haisom/.npm/_logs/2023-12-09T08_32_49_043Z-debug-0.log

**Comment by haisom2022** [comment]
我用 npm install --legacy-peer-deps 之后，再一次npm run build报下面这些错误
ERROR in ./src/assets/element-variables.scss
Module build failed: ModuleBuildError: Module build failed: Error: Node Sass version 8.0.0 is incompatible with ^4.0.0.
    at getRenderFuncFromSassImpl (/Users/haisom/wwwroot/local.test/web_src/node_modules/sass-loader/dist/index.js:165:13)
    at Object.loader (/Users/haisom/wwwroot/local.test/web_src/node_modules/sass-loader/dist/index.js:79:18)
    at /Users/haisom/wwwroot/local.test/web_src/node_modules/webpack/lib/NormalModule.js:195:19
    at /Users/haisom/wwwroot/local.test/web_src/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/haisom/wwwroot/local.test/web_src/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/Users/haisom/wwwroot/local.test/web_src/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/haisom/wwwroot/local.test/web_src/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at /Users/haisom/wwwroot/local.test/web_src/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at /Users/haisom/wwwroot/local.test/web_src/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:70:14
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
 @ ./src/assets/element-variables.scss
 @ ./src/main.js

ERROR in ./src/assets/fontawesome.scss
Module build failed: ModuleBuildError: Module build failed: Error: Node Sass version 8.0.0 is incompatible with ^4.0.0.
    at getRenderFuncFromSassImpl (/Users/haisom/wwwroot/local.test/web_src/node_modules/sass-loader/dist/index.js:165:13)
    at Object.loader (/Users/haisom/wwwroot/local.test/web_src/node_modules/sass-loader/dist/index.js:79:18)
    at /Users/haisom/wwwroot/local.test/web_src/node_modules/webpack/lib/NormalModule.js:195:19
    at /Users/haisom/wwwroot/local.test/web_src/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/haisom/wwwroot/local.test/web_src/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/Users/haisom/wwwroot/local.test/web_src/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/haisom/wwwroot/local.test/web_src/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at /Users/haisom/wwwroot/local.test/web_src/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at /Users/haisom/wwwroot/local.test/web_src/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:70:14
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
 @ ./src/assets/fontawesome.scss
 @ ./src/main.js

ERROR in ./src/assets/fontawesome.scss
Module build failed: ModuleBuildError: Module build failed: Error: Node Sass version 8.0.0 is incompatible with ^4.0.0.
    at getRenderFuncFromSassImpl (/Users/haisom/wwwroot/local.test/web_src/node_modules/sass-loader/dist/index.js:165:13)
    at Object.loader (/Users/haisom/wwwroot/local.test/web_src/node_modules/sass-loader/dist/index.js:79:18)
    at /Users/haisom/wwwroot/local.test/web_src/node_modules/webpack/lib/NormalModule.js:195:19
    at /Users/haisom/wwwroot/local.test/web_src/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/haisom/wwwroot/local.test/web_src/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/Users/haisom/wwwroot/local.test/web_src/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/haisom/wwwroot/local.test/web_src/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/haisom/wwwroot/local.test/web_src/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/haisom/wwwroot/local.test/web_src/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:40:15)
    at /Users/haisom/wwwroot/local.test/web_src/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:77:9
    at /Users/haisom/wwwroot/local.test/web_src/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)
 @ ./src/main.js 25:0-35

ERROR in ./src/assets/element-variables.scss
Module build failed: ModuleBuildError: Module build failed: Error: Node Sass version 8.0.0 is incompatible with ^4.0.0.
    at getRenderFuncFromSassImpl (/Users/haisom/wwwroot/local.test/web_src/node_modules/sass-loader/dist/index.js:165:13)
    at Object.loader (/Users/haisom/wwwroot/local.test/web_src/node_modules/sass-loader/dist/index.js:79:18)
    at /Users/haisom/wwwroot/local.test/web_src/node_modules/webpack/lib/NormalModule.js:195:19
    at /Users/haisom/wwwroot/local.test/web_src/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/haisom/wwwroot/local.test/web_src/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/Users/haisom/wwwroot/local.test/web_src/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/haisom/wwwroot/local.test/web_src/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/haisom/wwwroot/local.test/web_src/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/haisom/wwwroot/local.test/web_src/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:40:15)
    at /Users/haisom/wwwroot/local.test/web_src/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:77:9
    at /Users/haisom/wwwroot/local.test/web_src/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)
 @ ./src/main.js 8:0-41

  Build failed with errors.

**Comment by star7th** [comment]
我目前开发环境使用的node版本是 v14.21.3  ，你可以尝试使用这个版本。

**Comment by ZAIDU-Miren** [comment]
> 我目前开发环境使用的node版本是 v14.21.3 ，你可以尝试使用这个版本。

你好，我目前是v18.17.1

也是报错
![image](https://github.com/star7th/showdoc/assets/92215296/ff7d4a77-72a9-4225-ab53-3441bf9104cb)

换node版本就可以解决嘛。貌似是webpack依赖兼容问题啊

**Comment by star7th** [comment]
由于历史问题，建议使用 node 14。node 可以多版本共存，可以搜一下网络。

肖书南 ***@***.***>于2024年1月21日 周日上午12:04写道：
