### ISSUE TITLE
项目主页（item#show#index.vue）点击回退报错

### ISSUE THREAD

**Issue by hxxian** [star7th/showdoc#2124]
报错信息如下：
vendor.339f5a1f86786a88b9d4.js:63 TypeError: Cannot read properties of null (reading 'parentNode')
    at removeMark (eval at 0rW9 (vendor.339f5a1f86786a88b9d4.js:31:9792), <anonymous>:1:6965)
    at watermark.remove (eval at 0rW9 (vendor.339f5a1f86786a88b9d4.js:31:9792), <anonymous>:1:7353)
    at o.beforeDestroy (app.f4db61493625d00c6cab.js:1:284061)
    at Ve (vendor.339f5a1f86786a88b9d4.js:63:11338)
    at nn (vendor.339f5a1f86786a88b9d4.js:63:25295)
    at e.$destroy (vendor.339f5a1f86786a88b9d4.js:63:34705)
    at destroy (vendor.339f5a1f86786a88b9d4.js:63:20669)
    at b (vendor.339f5a1f86786a88b9d4.js:63:58077)
    at w (vendor.339f5a1f86786a88b9d4.js:63:58259)
    at vendor.339f5a1f86786a88b9d4.js:63:59815

**Comment by hxxian** [comment]
> 如果没影响使用的，可以不用管。

还是有点小问题的，鼠标后退到上一页时，浏览器url便了，页面却没有刷新，需要手动刷新才正常。

**Comment by star7th** [comment]
不支持鼠标的前进一页或者后退一页。即使没报错也不支持。跟这个没关系。
