### ISSUE TITLE
基于Docker构建项目，数据库创建失败

### ISSUE THREAD

**Issue by gam2046** [star7th/showdoc#253]
检出master分支与标签v2.1.1均为一样的结果。

容器启动无问题，注册用户失败。

# 环境

请求URI `index.php?s=/api/user/register` 服务端响应404

响应体：
```
SQLSTATE[HY000]: General error: 1 no such table: user
错误位置
FILE: /var/www/html/ThinkPHP/Library/Think/Db/Driver.class.php 　LINE: 156

TRACE
#0 /var/www/html/ThinkPHP/Library/Think/Db/Driver.class.php(156): PDO->prepare('SELECT * FROM u...')
#1 /var/www/html/ThinkPHP/Library/Think/Db/Driver.class.php(946): Think\Db\Driver->query('SELECT * FROM u...', false)
#2 /var/www/html/ThinkPHP/Library/Think/Model.class.php(759): Think\Db\Driver->select(Array)
#3 /var/www/html/server/Application/Api/Model/UserModel.class.php(12): Think\Model->find()
#4 /var/www/html/server/Application/Api/Controller/UserController.class.php(16): Api\Model\UserModel->isExist('gam2046')
#5 [internal function]: Api\Controller\UserController->register()
#6 /var/www/html/ThinkPHP/Library/Think/App.class.php(173): ReflectionMethod->invoke(Object(Api\Controller\UserController))
#7 /var/www/html/ThinkPHP/Library/Think/App.class.php(110): Think\App::invokeAction(Object(Api\Controller\UserController), 'register')
#8 /var/www/html/ThinkPHP/Library/Think/App.class.php(204): Think\App::exec()
#9 /var/www/html/ThinkPHP/Library/Think/Think.class.php(120): Think\App::run()
#10 /var/www/html/ThinkPHP/ThinkPHP.php(97): Think\Think::start()
#11 /var/www/html/server/index.php(24): require('/var/www/html/T...')
#12 {main}
```

查看创建的数据库文件长度为0
```
# whoami
root
# ls -la
total 84
drwxrwxrwx 1 www-data www-data 4096 Apr 22 10:38 .
drwxr-xr-x 1 root     root     4096 Apr 22 10:38 ..
drwxrwxrwx 1 root     root     4096 Apr 22 10:38 .git
-rwxrwxrwx 1 root     root      382 Apr 22 10:34 .gitignore
-rwxrwxrwx 1 root     root      260 Apr 22 10:34 .htaccess
drwxrwxrwx 1 root     root     4096 Apr 22 10:38 Application
-rwxrwxrwx 1 root     root      397 Apr 22 10:34 Dockerfile
-rwxrwxrwx 1 root     root     1743 Apr 22 10:34 LICENSE.txt
drwxrwxrwx 1 root     root     4096 Apr 22 10:38 Public
-rwxrwxrwx 1 root     root     4058 Apr 22 10:34 README.md
drwxrwxrwx 2 root     root     4096 Apr 22 13:21 Sqlite
drwxrwxrwx 1 root     root     4096 Apr 22 10:38 ThinkPHP
-rwxrwxrwx 1 root     root      563 Apr 22 10:34 composer.json
-rwxrwxrwx 1 root     root     4286 Apr 22 10:34 favicon.ico
-rwxrwxrwx 1 root     root     1009 Apr 22 10:34 index.php
drwxrwxrwx 1 root     root     4096 Apr 22 13:21 install
-rwxrwxrwx 1 root     root       30 Apr 22 10:34 robots.txt
drwxrwxrwx 1 root     root     4096 Apr 22 10:38 server
drwxrwxrwx 1 root     root     4096 Apr 22 10:38 web
drwxrwxrwx 1 root     root     4096 Apr 22 10:38 web_src
# cd Sqlite
# ls -la
total 8
drwxrwxrwx 2 root     root     4096 Apr 22 13:21 .
drwxrwxrwx 1 www-data www-data 4096 Apr 22 10:38 ..
-rw-r--r-- 1 www-data www-data    0 Apr 22 13:21 showdoc.db.php
```

日志：
```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.10.101.1. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.10.101.1. Set the 'ServerName' directive globally to suppress this message
[Sun Apr 22 13:20:58.595382 2018] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/5.6.35 configured -- resuming normal operations
[Sun Apr 22 13:20:58.595427 2018] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
10.10.0.2 - - [22/Apr/2018:13:21:06 +0000] "GET / HTTP/1.1" 302 353 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"

后续为正常http请求信息，省略
```

Docker 版本：
```
$ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:48 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

# 猜测原因 

由于Dockerfile中未指定`USER`，故默认使用了root用户，而当web容器启动时，未以root用户运行（通过docker exec 进入容器观察，apache2进程是以`www-data`身份运行），因此造成web容器没有对数据库有读写权限。

建议在docker中可以统一使用root身份进行，本身容器在隔离环境中运行，再以多用户区分，个人感觉意义不是很大。

**Comment by star7th** [comment]
咦，不对呀。Dockerfile里明明执行了 RUN chmod -R 777 /var/www/html/ ，不应再有权限问题。

**Comment by gam2046** [comment]
确实，问题出在了容器内/Sqlite目录，是我通过宿主环境注入的（为了持久化保存且便于升级），而docker中的RUN命令是在构建镜像时完成的。故造成了权限问题。

不过个人还是建议在容器内没有很大的必要性再设置多个账号。就在刚才检索的时候，发现php的镜像中使用www-data身份是硬编码写死的

**Comment by gam2046** [comment]
补充一句，dockerfile中的RUN是在构建镜像的时候执行的，因此在我的例子中，镜像中的/var/www/html是777的权限，但是实际执行时，由于我通过数据卷挂载了一个目录进去，默认情况下，宿主环境下的docker用户创建出来的目录的所有者uid为0，即root。此时我挂载进去的数据卷覆盖了镜像中本身的目录，因此造成的权限问题。

解决方案是，把这类权限设置放在CMD中执行，即在容器启动时进行设置，这样无论用户是否挂载数据卷均不影响。
