### ISSUE TITLE
进入项目后，选中页面，再点目录管理直接卡死（去掉选中页面步骤是正常的）

### ISSUE THREAD

**Issue by Vrapile** [star7th/showdoc#714]
进入项目后，选中页面，再点目录管理直接卡死，
如果进入项目后，直接点目录管理是正常的，点过页面后，再点目录管理，直接卡死

**Comment by star7th** [comment]
今天有个人也给我邮箱反馈了这个。
目测跟浏览器兼容有关。如果是使用ie或者360浏览器的兼容模式会有此问题。如果是使用谷歌火狐浏览器或者360的极速模式则没问题。

Vrapile <notifications@github.com>于2019年12月31日 周二下午7:21写道：

**Comment by Vrapile** [comment]
我用的就是谷歌浏览器

**Comment by star7th** [comment]
你清理缓存后看可不可以。然后不行的话提供下浏览器版本

Vrapile <notifications@github.com> 于2020年1月2日周四 上午9:39写道：

**Comment by star7th** [comment]
另外同时测试下官网的有没有问题 https://www.showdoc.cc/

Chen Xing <xing7th@gmail.com> 于2020年1月2日周四 上午9:42写道：

**Comment by Vrapile** [comment]
官网没有登录账号呀

**Comment by star7th** [comment]
注册一个测试下。

Vrapile <notifications@github.com> 于2020年1月2日周四 上午9:45写道：

**Comment by Vrapile** [comment]
Chrome版本是：
版本 62.0.3202.94（正式版本） （32 位）

**Comment by Vrapile** [comment]
官网一样会卡

**Comment by Vrapile** [comment]
比如这个：
https://www.showdoc.cc/630883351827101
进去直接点管理目录，就卡死了

**Comment by star7th** [comment]
我怀疑你使用了什么不兼容的浏览器扩展。尝试使用谷歌浏览器干净的隐身模式看还有没有问题

**Comment by Vrapile** [comment]
F12看到报了这个
vue.min.js:6 TypeError: parameter 1 is not of type "Element".
    at e.observe (https://cdn.staticfile.org/element-ui/2.13.0/index.js:1:21257)
    at e.k.(anonymous function) [as observe] (https://cdn.staticfile.org/element-ui/2.13.0/index.js:1:22860)
    at Ye (https://cdn.staticfile.org/element-ui/2.13.0/index.js:1:88007)
    at a.bindEvents (https://cdn.staticfile.org/element-ui/2.13.0/index.js:1:234246)
    at a.mounted (https://cdn.staticfile.org/element-ui/2.13.0/index.js:1:237184)
    at He (https://cdn.staticfile.org/vue/2.6.10/vue.min.js:6:11397)
    at Yt (https://cdn.staticfile.org/vue/2.6.10/vue.min.js:6:25339)
    at Object.insert (https://cdn.staticfile.org/vue/2.6.10/vue.min.js:6:20368)
    at k (https://cdn.staticfile.org/vue/2.6.10/vue.min.js:6:60187)
    at a.e.nodeOps [as __patch__] (https://cdn.staticfile.org/vue/2.6.10/vue.min.js:6:61547)

**Comment by Vrapile** [comment]
我发给同事，同事电脑谷歌浏览器是正常可以打开目录管理的，那原因就是我的浏览器问题了
用隐身模式也还是一样，之前有两个插件postman和Vue.js devtools，关掉了也没反应，我回复完重启浏览器看看

**Comment by Vrapile** [comment]
同事的都可以，看来我得重新安装浏览器了，感谢支持！

**Comment by star7th** [comment]
已重写了目录管理功能，增加拖动排序和转移层级功能。

**Comment by Vrapile** [comment]
向大佬致敬！
